---
- name: Power ON "{{ rru }}" PDU outlet
  ansible.builtin.command: "rhubarbe pdu on {{ rru }}"
  changed_when: true

- name: Wait for a Benetel RRU to be ready
  ansible.builtin.pause:
    seconds: 210
  when: rru in ['benetel1', 'benetel2'] and ran | lower in ['srsran', 'oai']

- name: Prepare the selected Benetel RRU
  ansible.builtin.command: "/usr/local/bin/prepare-{{ rru }}-for-{{ ran | lower }}.sh"
  when: rru in ['benetel1', 'benetel2'] and ran | lower in ['srsran', 'oai']
  register: prepare_rru_output
  changed_when: true

- name: Report R2Lab radio preparation
  ansible.builtin.debug:
    msg: "{{ prepare_rru_output.stdout | default('No additional preparation required') }}"

- name: Verify the selected RRU PDU status
  ansible.builtin.command: "rhubarbe pdu status {{ rru }}"
  register: pdu_status
  changed_when: false

- name: Report R2Lab PDU status
  ansible.builtin.debug:
    var: pdu_status.stdout
